version: '3.4'

services:
  acronymns:
    image: fatiu/acronymns
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8001:8001

